//
// QueryChat200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "ChatOnMacWebAPI.QueryChat200Response")
public typealias QueryChat200Response = ChatOnMacWebAPI.QueryChat200Response

extension ChatOnMacWebAPI {

public struct QueryChat200Response: Codable, JSONEncodable, Hashable {

    public var response: String

    public init(response: String) {
        self.response = response
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case response
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(response, forKey: .response)
    }
}

}
