//
// QueryBalanceDefaultResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "ChatOnMacWebAPI.QueryBalanceDefaultResponse")
public typealias QueryBalanceDefaultResponse = ChatOnMacWebAPI.QueryBalanceDefaultResponse

extension ChatOnMacWebAPI {

public struct QueryBalanceDefaultResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var code: String
    public var issues: [QueryBalanceDefaultResponseIssuesInner]?

    public init(message: String, code: String, issues: [QueryBalanceDefaultResponseIssuesInner]? = nil) {
        self.message = message
        self.code = code
        self.issues = issues
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case code
        case issues
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(issues, forKey: .issues)
    }
}

}
