//
// QueryBalance200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "ChatOnMacWebAPI.QueryBalance200Response")
public typealias QueryBalance200Response = ChatOnMacWebAPI.QueryBalance200Response

extension ChatOnMacWebAPI {

public struct QueryBalance200Response: Codable, JSONEncodable, Hashable {

    public var balance: Double

    public init(balance: Double) {
        self.balance = balance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balance, forKey: .balance)
    }
}

}
